language: python

python:
- '2.6'
- '2.7'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq pandoc

install: pip install -r requirements.txt

script: ./build.sh

deploy:
  provider: pypi
  user: odi
  password:
    secure: MU3ZQ4rcpsXo0xIYSWXBfaKTAPn1IrL7AEcH231sseFV1RVmdC96Sfmtc2llvD9Eoc0KJpdW0Vy50azNqAMJwXCt/q3gagfao1PTnAEbklU+g1s2PTqW401E95Qm6w192WzWk/q0dy3SJwxEQt023QR78K+nEcYaCdLWDHjR2hY=
  on:
    branch: master
    python: 2.7
    repo: metaodi/osmapi
